### ISSUE TITLE
Windows7 下报错内容如图

### ISSUE THREAD

**Issue by ghost** [ZSAIm/iqiyi-parser#1]
![snipaste_20](https://user-images.githubusercontent.com/21291399/45198537-9b4c2800-b299-11e8-9275-eb6276a9862d.png)

**Comment by ZSAIm** [comment]
在编译的目录下需要以下两个文件，你是不是只下载了main.exe？
ArrayBuffer.js
pcweb.js

**Comment by ghost** [comment]
下载全部东西.
我尝试运行根目录下的main.py,发现里面要安装pip install colorama
之后再次尝试运行报错如果如下:

" https://www.iqiyi.com/v_19rrdw0xdo.html "
Traceback (most recent call last):
  File "main.py", line 246, in <module>
    main()
  File "main.py", line 191, in main
    videoname, _msg = iqiyi.parse(url, global_bids)
  File "C:\Users\Administrator\Desktop\iqiyi-parser-master\iqiyi_parse.py", line 120, in parse
    msg = json_msg['data']['program']['video']
TypeError: string indices must be integers


我正在尝试打印['data']['program']['video']这三个数据,看是哪个类型出错了

**Comment by ZSAIm** [comment]
TypeError: string indices must be integers
显示json_msg是一个文本，可以把json_msg打印出来发来看看吗？

**Comment by ghost** [comment]
我不是很懂Python, 用print()打印时发现并没有输出到控制台,我要怎样打印?

        for bid in bids:
            json_msg = self.__parse(tvid, vid, uid, bid)
            if not json_msg:
                continue
            print("data:%s, program:%s, video:%s" %(['data'],['program'],['video']))
            msg = json_msg['data']['program']['video']

这样可以吗?

**Comment by ZSAIm** [comment]
直接
print json_msg

**Comment by ghost** [comment]
{u'code': u'A00000', u'data': {u'program': u'', u'tvid': 811789200, u'cid': 1, u'st': 502, u'content': {u'crr': 0, u'exclusive': 0, u'bossStatus': 0, u'contentType': 1, u'isRs': 0, u'vipTypes': [0], u'thdt': 1, u'isProduced': 0, u'cids': [1, 11, 20001, 27815, 28997]}, u'p': {u'lgh': [], u'wmarkPos': 0, u'ca': 0, u'tsl': u'', u'bt': -1, u'raudio': False, u'et': -1, u'lgp': 0, u'pano': {u'type': 1}}, u'parts': {}, u'bmsg': {u'mid': u'', u'sp': u'091410101', u't': u'20180907151000', u'f': u'web'}, u'ctl': {u'cached': True, u'ip': u'95.169.2.71', u'log': True, u'qd_vipdyn': 0}, u'aid': 811789200, u'svp': []}}

**Comment by ZSAIm** [comment]
先确认一下，你使用的是
python2.7版本？
你现在抓取的地址是https://www.iqiyi.com/v_19rr7pi4k4.html？

**Comment by ghost** [comment]
[C:\Users\Administrator\Desktop\iqiyi-parser-master]$ python --version
Python 2.7.13

https://www.iqiyi.com/v_19rrdw0xdo.html

**Comment by ZSAIm** [comment]
我这里可以解析。
![_20180907153005](https://user-images.githubusercontent.com/34599927/45205087-b9bf1d00-b2b3-11e8-9c2d-0eb9dd9e1ba2.png)
你尝试重新把代码克隆一下。然后再试一下。

**Comment by ghost** [comment]
重新检出仍然报错,建议在新电脑上尝试一下.

**Comment by ZSAIm** [comment]
在Win10系统上的运行结果，依然没问题。。
![1](https://user-images.githubusercontent.com/34599927/45206742-584d7d00-b2b8-11e8-871c-91192cd4298e.png)
