### ISSUE TITLE
大佬，我有会员怎么自己拼接啊？

### ISSUE THREAD

**Issue by wakichen** [ZSAIm/iqiyi-parser#10]

**Comment by ZSAIm** [comment]
这个程序只解析游客模式下的哦，如果你有兴趣可以按照项目下的PDF下方式抓包，然后改一下parse.py下提交数据。我手里没会员就不搞了。

**Comment by xlpxxx** [comment]
加个cookie就能解析vip视频

**Comment by ZSAIm** [comment]
已允许导入Cookie功能。
下载最新的release吧。
