### ISSUE TITLE
程序已失效

### ISSUE THREAD

**Issue by YFTX2015** [ZSAIm/iqiyi-parser#11]
爱奇艺又更新了算法，程序解析已失效。

**Comment by ZSAIm** [comment]
解析并没问题，只是第三方模块colorama的问题。这段时间会尽量抽点时间写个GUI界面，放弃使用colorama。

**Comment by YFTX2015** [comment]
这我就不懂了。反正用你编的这个程序在win10下能够把爱奇艺视频清晰度解析出来，但是准备下载的时候，一输完前面的编号按回车键就闪退。另外用soarqin编写的iQ2解析内地的视频已经完全失效，用维棠加第三方插件解析台湾爱奇艺的视频还有效。

**Comment by ZSAIm** [comment]
发一下你要解析的地址，我看一下。
还有，注意会员是搞不来的哦，这只是解析游客下的。

**Comment by YFTX2015** [comment]
https://www.iqiyi.com/v_19rsihc7u4.html
https://www.iqiyi.com/v_19rsihangs.html

**Comment by YFTX2015** [comment]
Fatal Error!
Failed to execute script main
一点下载就出现这个

**Comment by ZSAIm** [comment]
这个视频观看需要会员。。不能用，因为这个解析就是基于游客模式的。
（以后有时间了可能会去支持加入会员的Cookie。。）

**Comment by YFTX2015** [comment]
原来会员视频和普通视频的地址有区别啊，这我都不晓得。

**Comment by YFTX2015** [comment]
我觉得要下会员视频，要么就是有资源嗅探器在会员状态下通过把视频时间轴分成四段或八段，分别嗅探，要么就是有播放1080P清晰度的在线解析接口，然后通过火狐的video downloadhelper或者flash video downloader来下载。

**Comment by YFTX2015** [comment]
可惜现在都找不到有效的工具和接口。另外，现在在动漫花园上有一个叫c.c动漫的发布者能够成功解析爱奇艺会员画质视频，但是不会提供下载方法。

**Comment by ZSAIm** [comment]
事实上这个项目并不是使用嗅探方式，而是模拟浏览器提交数据以获得下载地址。所以理论上只需要在会员的基础上进行抓包，分析会员的情况下所提交的数据。模拟提交便能得到服务器返回视频地址的响应。

**Comment by ZSAIm** [comment]
最新的release已支持导入Cookie。
详情看README.MD。
