### ISSUE TITLE
能支持cookie吗?

### ISSUE THREAD

**Issue by a88wyzz** [ZSAIm/iqiyi-parser#12]
之前有看到别的软件可以利用cookie中的参数解析出m3u8地址，不知道这个能实现吗~~

还有能不能调用ffmpeg合并分段为mp4格式，原始格式拖动进度条卡顿。

**Comment by ZSAIm** [comment]
1. 这是以PC端H5播放方式为入口点解析出来的地址，所以应该没有m3u8，而且目前是以在游客模式下进行的，所以并不支持Cookie，理论上是可以实现。
2. 可以实现调用ffmpeg。

现在不行，，没时间，以后可能会做。

**Comment by a88wyzz** [comment]
大神，如果有可能的话请加上cookie功能，然后由使用者决定用不用cookie

**Comment by ZSAIm** [comment]
最新的release已支持导入Cookie。
使用方法看README.MD。
