### ISSUE TITLE
卡进度25%怎么回事？

### ISSUE THREAD

**Issue by a88wyzz** [ZSAIm/iqiyi-parser#13]
![bz](https://user-images.githubusercontent.com/35162785/55147143-d011c500-5180-11e9-8a64-c16f7ad82a93.gif)

**Comment by a88wyzz** [comment]
打勾的是600解析出500 ？？

**Comment by ZSAIm** [comment]
1. 你查看在下载目录下视频文件是否被占用了。也就是 F:/ffmepg下面下载完成的分段视频。
2. 最后卡在的25%是卡在合并文件上了。尝试下删除视频文件再重新解析下载。
3. 打勾的600并不是实际上的600，指的是最大bid值是600。 

还有，这是否是频繁出现的情况？

**Comment by a88wyzz** [comment]
如果不选择下载目录，是不是下载到当前目录（这个我没试），我是测试了2次的结果一样，F:/ffmepg目录并没有被占用。

**Comment by ZSAIm** [comment]
卡在25%问题已经修复了。。
如果不选择是会下载到程序所在目录。
