### ISSUE TITLE
执行脚本失败

### ISSUE THREAD

**Issue by abstyledsq** [ZSAIm/iqiyi-parser#14]
win 10 64 解析地址无效，关闭面板后会报错呢 求大佬解答~~（非专业人士）

**Comment by ZSAIm** [comment]
留一下你解析的视频是否是需要会员的。
因为现在这程序是以游客下进行的解析，所以不具备解析下载会员视频的功能。

**Comment by abstyledsq** [comment]
> 留一下你解析的视频是否是需要会员的。
> 因为现在这程序是以游客下进行的解析，所以不具备解析下载会员视频的功能。

不哦~ 大佬 不需要会员 且 我是游客未登陆呢 呜呜

**Comment by abstyledsq** [comment]
> 留一下你解析的视频是否是需要会员的。
> 因为现在这程序是以游客下进行的解析，所以不具备解析下载会员视频的功能。

大佬 我是随便一个视频都会失败，包括几分钟的短视频哈，另 有机会能出个mac版不，跪求了

**Comment by ZSAIm** [comment]
1. 如果直接关闭面板是会报错，这是个小bug，执行流程没弄好，但这不会太影响使用。下次会和其他bug一起修复。
2. 现在先用着，能解析下载就Ok咯，如果不行正常解析下载的话，你说下是在哪一步骤出现了什么错误现象。
3. 。。。mac的出不来，电脑没装黑苹果，而且没用过mac，整不来。。理论上linux是兼容的，只要代码重新编译应该问题不大。

**Comment by abstyledsq** [comment]
> 1. 如果直接关闭面板是会报错，这是个小错误，执行流程没弄好，但这不会太影响使用。下次会和其他错误一起修复。
> 2. 现在先用着，能解析下载就确定咯，如果不行正常解析下载的话，你说下是在哪一步骤出现了什么错误现象。
> 3. ... MAC的出不来，电脑没装黑苹果，而且没用过Mac上，整不来..理论上的Linux是兼容的，只要代码重新编译应该问题不大。

感恩大佬的回复~ 下载的问题是这样哈，就是我把游客链接复制进去，没反应，一直没有，然后关闭面板就报错啦~就是这样

**Comment by ZSAIm** [comment]
1. 选择你要解析的清晰度（默认已选600）
2. 复制想要解析的地址。
3. 按下解析按钮。
4. 选中列表中想要下载的选项。
5. 点击下载选中项进行下载。
