### ISSUE TITLE
不能解析免费视频的1080P格式？

### ISSUE THREAD

**Issue by a88wyzz** [ZSAIm/iqiyi-parser#15]
不能解析免费视频的1080P格式？
可以参考一下annie，可以解析免费视频的1080P格式~~~
https://github.com/iawia002/annie
还有能不能一个视频下载完成后，返回到主界面？？
导入视频地址列表功能？

**Comment by xlpxxx** [comment]
不是电视剧只有大多数都是360p，720p很少，电影大多数都是720p，少数1080p，苹果设备能看4k

解析出来的vip视频，可以用迅雷下载，分段的

**Comment by ZSAIm** [comment]
1. 已经支持下载免费视频的1080P，并且支持导入会员COOKIE等，查看README.MD更新说明。
2. 据我了解，现在的PC，H5网页端暂不支持选择2K，4K。最高支持1080p。等什么时候PC端支持了2K，4K再说吧。
3. 可以实现循环流程，但是我应该是不做了。
4. 不打算做批量视频解析下载功能。

**Comment by xlpxxx** [comment]
mac那个标识支持2k，但是不是所有都有2k

**Comment by xlpxxx** [comment]
01010031010000000000   这串标记，应该是win系统的，另外mac和ipad的是支持2k  4k的，用迅雷是能下载到vip视频的

**Comment by ZSAIm** [comment]
那可能是我孤陋寡闻了。。。没用过这些设备都不知道支持这些东西~~

**Comment by xlpxxx** [comment]
01010031010000000000   在js内搜索一下这串代码，你会发现其他的标识代码的

**Comment by ZSAIm** [comment]
我知道有这一标识符，以为只是简单的给服务器区分用户设备的。没想到还是对mac和ipad特别照顾了。。
