### ISSUE TITLE
啥时候上传啊

### ISSUE THREAD

**Issue by wakichen** [ZSAIm/iqiyi-parser#19]
文件啥时候上传啊，坐等大佬

**Comment by ZSAIm** [comment]
我还想先做个JSCaller再上传的，既然这样那我先上传个可导入Cookie解析视频的release，下载器先砍掉。
等过几天完善了下载器再上传新的。。

**Comment by wakichen** [comment]
大佬有联系方式吗

**Comment by wakichen** [comment]
大佬请问这样的视频怎么下载啊？解析不到1080的720的也可以https://www.iqiyi.com/v_19rqye2yyc.html

**Comment by ZSAIm** [comment]
。。。。兄弟这是付费视频，没有购买是没有权限获取的。。服务器不给你数据啊
服务器返回：
```
 u'已登录用户：不允许试看鉴权失败'
```

**Comment by wakichen** [comment]
大佬问个问题，比如https://www.iqiyi.com/v_19rqxy6yvs.html这个链接，19rqxy6yvs这个是怎么算的啊？怎么算的和他的tvId是对应的啊？

**Comment by wakichen** [comment]
> ....兄弟这是付费视频，没有购买是没有权限获取的..不服务器给你数据啊
> 服务器报道查看：
> 
> ```
>  u'已登录用户：不允许试看鉴权失败'
> ```

我有返回的数据，怎么加你好友啊？

**Comment by ZSAIm** [comment]
> > ....兄弟这是付费视频，没有购买是没有权限获取的..不服务器给你数据啊
> > 服务器报道查看：
> > ```
> >  u'已登录用户：不允许试看鉴权失败'
> > ```
> 
> 我有返回的数据，怎么加你好友啊？

联系就邮箱吧： zzsaim@163.com

**Comment by wakichen** [comment]
> > > ....兄弟这是付费视频，没有购买是没有权限获取的..服务器不给你数据啊
> > > 服务器报道查看：
> > > ```
> > >  u'已登录用户：不允许试看鉴权失败'
> > > ```
> > 
> > 
> > 我有返回的数据，怎么加你好友啊？
> 
> 联系就邮箱吧：[zzsaim@163.com](mailto:zzsaim@163.com)

大佬好像不支持4K啊

**Comment by ZSAIm** [comment]
> > > > ....兄弟这是付费视频，没有购买是没有权限获取的..服务器不给你数据啊
> > > > 服务器报道查看：
> > > > ```
> > > >  u'已登录用户：不允许试看鉴权失败'
> > > > ```
> > > 
> > > 
> > > 我有返回的数据，怎么加你好友啊？
> > 
> > 
> > 联系就邮箱吧：[zzsaim@163.com](mailto:zzsaim@163.com)
> 
> 大佬好像不支持4K啊

WIN的H5端确实不支持2K，4K。。。
听说MAC和PAD能支持2K，4K，但是只能是听说了。可能是README.MD有所误导，已经改正了。

**Comment by wakichen** [comment]
> > > > > ....兄弟这是付费视频，没有购买是没有权限获取的..服务器不给你数据啊
> > > > > 服务器报道查看：
> > > > > ```
> > > > >  u'已登录用户：不允许试看鉴权失败'
> > > > > ```
> > > > 
> > > > 
> > > > 我有返回的数据，怎么加你好友啊？
> > > 
> > > 
> > > 联系就邮箱吧：[zzsaim@163.com](mailto:zzsaim@163.com)
> > 
> > 
> > 大佬好像不支持4K啊
> 
> WIN的H5端确实不支持2K，4K。。。
> 听说MAC和PAD能支持2K，4K，但是只能是听说了。可能是README.MD有所误导，已经改正了。

### ###

**Comment by wakichen** [comment]
> > > > > > ....兄弟这是付费视频，没有购买是没有权限获取的..不服务器给你数据啊
> > > > > > 服务器报道查看：
> > > > > > ```
> > > > > >  u'已登录用户：不允许试看鉴权失败'
> > > > > > ```
> > > > > 
> > > > > 
> > > > > 我有返回的数据，怎么加你好友啊？
> > > > 
> > > > 
> > > > 联系就邮箱吧：[zzsaim@163.com](mailto:zzsaim@163.com)
> > > 
> > > 
> > > 大佬好像不支持4K啊
> > 
> > 
> > WIN的H5端确实不支持2K，4K ...... 
> > 听说MAC和PAD能支持2K，4K，但是只能是听说了。可能是README.MD有所误导，已经改正了。

[img]https://s2.ax1x.com/2019/04/13/ALmTqH.png[/img]
