### ISSUE TITLE
没法下载啊？闪退

### ISSUE THREAD

**Issue by wakichen** [ZSAIm/iqiyi-parser#2]

**Comment by ZSAIm** [comment]
不知道你实际的闪退情况，你可以在cmd里面执行main.exe，然后就不会闪退。然后把错误信息发过来。
建议你可以先参考问题一是不是你的情况。

**Comment by wakichen** [comment]
[http://upload.ouliu.net/i/20180907180820u46fd.jpeg](url)

**Comment by wakichen** [comment]
http://upload.ouliu.net/i/20180907180820u46fd.jpeg

**Comment by wakichen** [comment]
[](http://upload.ouliu.net/i/20180907180820u46fd.jpeg)

**Comment by wakichen** [comment]
![qq 20180907181100](https://user-images.githubusercontent.com/20485108/45213720-ec284480-b2ca-11e8-9b72-138e3b7b481b.jpg)
我按回车就出现这个的然后就闪退了，不知道啥情况

**Comment by ZSAIm** [comment]
程序目前还不支持下载vip视频，你所下载的是需要会员才能观看的视频。
