### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by a88wyzz** [ZSAIm/iqiyi-parser#20]
![QQ截图20190410183806](https://user-images.githubusercontent.com/35162785/55872587-f17ea200-5bbf-11e9-8f8d-afad955c9780.jpg)

关闭后就会出现这个提示

![QQ截图20190410184134](https://user-images.githubusercontent.com/35162785/55872738-4c17fe00-5bc0-11e9-9a6e-24e8a3e45cb0.jpg)

**Comment by a88wyzz** [comment]
![QQ截图20190410184802](https://user-images.githubusercontent.com/35162785/55873240-aa91ac00-5bc1-11e9-8db3-31ff40618d13.jpg)
还有问题，只要在双击打开main之前把浏览器的中爱奇艺的cookie复制到Cookie文本中，再点开main就会出现Failed to execute script main这个提示

**Comment by a88wyzz** [comment]
使用了cookie之后也下载不了，一直卡在那里不动
![QQ截图20190410190557](https://user-images.githubusercontent.com/35162785/55874034-c26a2f80-5bc3-11e9-8ad1-9862f0719508.jpg)

**Comment by YFTX2015** [comment]
解析出来的m3u8地址有误，放在m3u8 downloader里无法识别和下载。

**Comment by ZSAIm** [comment]
> 使用了cookie之后也下载不了，一直卡在那里不动
> ![QQ截图20190410190557](https://user-images.githubusercontent.com/35162785/55874034-c26a2f80-5bc3-11e9-8ad1-9862f0719508.jpg)

1. 第一个问题其实问题不大，是因为没有安全关闭程序。
2. 第二个问题应该就是导入的cookie可能会缺少一些字段引发的异常，但是没有进行异常处理。

以上两个问题如果确实是这样造成的话，下一个版本应该修复了哦，会在这几天内上传代码，还有release！！

**Comment by ZSAIm** [comment]
> 解析出来的m3u8地址有误，放在m3u8 downloader里无法识别和下载。

解析出来的m3u8并没有问题，因为爱奇艺提供的m3u8是全路径的，而m3u8 downloader好像是不支持全路径的m3u8的，你可以尝试在可以播放m3u8的播放器播放哦，如vlc什么的，已经尝试过vlc和迅雷看看了，可以使用；

**Comment by a88wyzz** [comment]
希望解析出的m3u8是一个链接地址，可以复制其他工具下载，而不是m3u8里的分片内容
还有，爱奇艺有h264和h265两种，可以选择吗？

**Comment by YFTX2015** [comment]
Star☆Twinkle光之美少女 第10集
1280x720
http://cache.m.iqiyi.com/mus/text/237523701/6111e0c288c64591690cf6eae59dc653/afbe8fd3d73448c9/2086832199/20190407/de/d4/6b6eb72242ef3e39e8a2a51f97c532c3.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=79047cf08279c46d28002307f63d14df&qypid=2252571700_04000000001000000000_4&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=2&ff=f4v&iswb=0&vf=d897853c89faa403f752202c86c4d458&np_tag=nginx_part_tag
1280x720
http://cache.m.iqiyi.com/mus/text/237523701/e3e1b38316993cc807580110884a848c/afbe8fd3d73448c9/2086832199/20190407/08/f4/9f66306a001a59c41d12cbf49bead320.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=ef6e7beb71a1d1698faa7ae3869995ed&qypid=2252571700_04000000001000000000_14&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=1&code=2&ff=dbts&iswb=0&vf=63f391c508f44971683be048c0b57493&np_tag=nginx_part_tag
896x504 H265
http://cache.m.iqiyi.com/mus/text/237523701/15c3261f353b0c90a14640cfcd9f44ab/afbe8fd3d73448c9/2086832199/20190407/fb/f1/c1e6d659127b133189c347e2ec103fc6.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=74a685dde7f44595b1f57c67e1bd164e&qypid=2252571700_04000000001000000000_21&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=1&ff=265ts&iswb=0&vf=d1e2a7cb451ee56867bb31771d297e6c&np_tag=nginx_part_tag
1920x1080 H265
http://cache.m.iqiyi.com/mus/text/237523701/2f49edc9fecf31fc2aeb3f88f6da79cb/afbe8fd3d73448c9/2086832199/20190407/98/0c/d2990e8cb43d4719dca9abd4d63f42e9.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=be15f3a7a9ce530c3aa1e907e5a15829&qypid=2252571700_04000000001000000000_18&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=1&ff=265ts&iswb=0&vf=53051222d7d678168c7eea87ba208e5e&np_tag=nginx_part_tag
384x216
http://cache.m.iqiyi.com/mus/text/237523701/dcf47649ba4e1b62fcb4e63567df4a00/afbe8fd3d73448c9/2086832199/20190407/11/6c/ec8099dcb2bcf1e76026557ca31e7f22.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=556e5cfd394e905250164ae9b9da064f&qypid=2252571700_04000000001000000000_96&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=2&ff=f4v&iswb=0&vf=74c3b5a73a5624a6025d3887bec1a301&np_tag=nginx_part_tag
1920x1080
http://cache.m.iqiyi.com/mus/text/237523701/5a5cc3920389cecfe121e5c2f449b7af/afbe8fd3d73448c9/2086832199/20190407/a2/30/6ed2dc3e5bc197576b416d313ba46d3d.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=474be10b03e71de714b963f1c4458e7d&qypid=2252571700_04000000001000000000_5&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=2&ff=f4v&iswb=0&vf=d9127cd087565f15864353998f253c89&np_tag=nginx_part_tag
896x504
http://cache.m.iqiyi.com/mus/text/237523701/048a43af3a7692e2acac044e41a9b224/afbe8fd3d73448c9/2086832199/20190407/11/0f/30b07ea2937694a6f63ef793208090ef.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=2c3c73abaa0d06c13f5f93a7072c7592&qypid=2252571700_04000000001000000000_2&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=2&ff=f4v&iswb=0&vf=448bf8999e1f60f58b95b7bc07d75be6&np_tag=nginx_part_tag
1280x720 H265
http://cache.m.iqiyi.com/mus/text/237523701/84f64526dd14ded0ae407d4bb4f1b6e5/afbe8fd3d73448c9/2086832199/20190407/39/9e/3f1666dc88e7dcefca165974a784eef6.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=0b6190ad761b6f52950ff4318b4b4671&qypid=2252571700_04000000001000000000_17&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=1&ff=265ts&iswb=0&vf=83d015c33a7f1803297295471726500a&np_tag=nginx_part_tag
640x360
http://cache.m.iqiyi.com/mus/text/237523701/4f2725ad57cf4fa133a6f24f970a6db3/afbe8fd3d73448c9/2086832199/20190407/50/32/246db4f2a557cf334cf5c4ee3c6882fa.m3u8?qd_originate=tmts_py&tvid=2252571700&bossStatus=2&qd_vip=1&px=d6ODznZ5X9llD8atid0lEpFQFf5PzZJatEb4fUALKzf1FiCNIKGOr2feFf0xGTG12v61&src=02022001010000000000&prv=0&previewType=1&previewTime=6&from=&qd_time=1555058935641&qd_p=ded13ca1&qd_asc=0540219527f8ced42297e56cbe81f88d&qypid=2252571700_04000000001000000000_1&qd_k=64e98571b433baf4111e53d3e0bd3a79&isdol=0&code=2&ff=f4v&iswb=0&vf=adb9a46303bc3ee12eab9711c5c10de4&np_tag=nginx_part_tag
这是用GetVideo-V1.3.0-20190324-芒果TV-h265解析出来的m3u8地址，放在m3u8 downloader里面就能正常下载。

**Comment by YFTX2015** [comment]
只不过失效时间很快，一般超过半分钟就会失效，你们应该都晓得的。建议下载并保存为m3u8文件，两小时都不得失效。

**Comment by ZSAIm** [comment]
> 只不过失效时间很快，一般超过半分钟就会失效，你们应该都晓得的。建议下载并保存为m3u8文件，两小时都不得失效。

。。好吧，你发的链接已经失效了，你可以尝试下载到本地，然后打开查看文件内容。
由于你说那个GetVideo和我这程序用的不是同一个方式请求的数据，所以获取到的信息的形式会有所区别，但最终的资源是一致的。事实上也可以通过修改m3u8达到兼容m3u8 downloader。但是我不做了。
程序解析到的m3u8并没有问题，确实是的那个m3u8 downloader软件不支持的问题。

**Comment by ZSAIm** [comment]
> 希望解析出的m3u8是一个链接地址，可以复制其他工具下载，而不是m3u8里的分片内容
> 还有，爱奇艺有h264和h265两种，可以选择吗？

1. 可以在网上搜一下相关的下载器。
2. 目前这程序并不能选择。
