### ISSUE TITLE
請問這有辦法解析台灣站的資源嗎

### ISSUE THREAD

**Issue by danny740211** [ZSAIm/iqiyi-parser#22]
可以解析台灣的資源嗎?
https://tw.iqiyi.com/v_19rsiyjj9g.html

**Comment by YFTX2015** [comment]
不行，只能解析大陆资源，跟getvideo.apk一样。要下台湾资源，首先要搭台湾梯子，然后用维棠导入惶心的最新解析插件方可下载，而且只有首次下载才能成功，解析二次及以上均失败。要不然清理完电脑垃圾后重启系统再解析，或许能成功。

**Comment by yisuiyue123** [comment]
惶心的最新解析插件在哪可以下载

**Comment by YFTX2015** [comment]
维棠官网> 第三方插件下载

**Comment by ZSAIm** [comment]
台湾的资源我们大陆这边不好做，因为没有这个测试环境。

**Comment by YFTX2015** [comment]
要付费梯子，不想给钱就放弃吧。免费又稳定的台湾梯子目前我还不晓得哪里有。
