### ISSUE TITLE
下載影片時出現問題

### ISSUE THREAD

**Issue by Toby413** [ZSAIm/iqiyi-parser#23]
影片分了8段,但是只能下載到其中5段
換了電腦,一直重新下載也一樣
![cap](https://user-images.githubusercontent.com/49644191/56131702-c2e73980-5fba-11e9-95cb-2dd60ede8dca.jpg)

**Comment by YFTX2015** [comment]
网络带宽几兆？慢了不行，因为地址很快会失效。

**Comment by Toby413** [comment]
測了一下 950mb
下面是視頻連結 :
https://www.iqiyi.com/v_19rrolq2v8.html

**Comment by YFTX2015** [comment]
千兆网么？还有网络运营商也很重要，稳定性差的也肯定不行。

**Comment by ZSAIm** [comment]
你先尝试下最新版的把，如果还是有问题就查看目录下的error.log把内容发出来看下。

**Comment by Toby413** [comment]
終於成功了!謝謝!
