### ISSUE TITLE
关于下载下来的格式问题。

### ISSUE THREAD

**Issue by YFTX2015** [ZSAIm/iqiyi-parser#24]
我记得以前用嗅探法下载下来的爱奇艺分段文件时f4v格式的，现在用这个工具下下来是ts格式的。f4v文件合并后时间长度准确无误，用任何播放器播放总时间长度都是一样。当ts文件合并成ts文件后，用potplayer播放时间基本准确，最多少一秒，而用win10自带的“电影和电视”播放，时间总是会少好几秒，这是咋回事？

**Comment by ZSAIm** [comment]
实际上可以选择下载f4v的，等下次更新再加上这个功能吧。
关于时间长度这个不太清楚，你看下是否有片段的损失把。。

**Comment by YFTX2015** [comment]
最好是能够支持下载或者转换成mp4文件，毕竟这种格式针对所有播放器来说，兼容性都是最好的。

**Comment by SeaHOH** [comment]
合并问题可以参考这里 https://github.com/zhangn1985/ykdl/issues/399#issuecomment-484337220

**Comment by YFTX2015** [comment]
我晓得这种通过命令的方式合并转换视频，不过稍显麻烦。我希望在软件里能够集成这种功能，简化转换流程，就像JJDown最近几个版本一样。

**Comment by SeaHOH** [comment]
只是解释错误合并命令导致 MPEG-1/2 格式的时间问题，不是让你手动输入命令合并。

TS 完整名称是 MPEG2-TS。

**Comment by YFTX2015** [comment]
看了你发的那篇评论文，看起来要合并正确时间长度的ts文件或者其它格式的文件，不是那么容易的事情，里面虽说法不一，但感觉合并的核心似乎还是要用到ffmpeg语法命令，由于我并不懂个中原理，所以还是希望在下载器里面能集成一个合并转换格式的功能，或者做一个独立的合并转换器，方便不懂行的人使用。

**Comment by SeaHOH** [comment]
> 不是让你手动输入命令合并。

就是给作者参考的。

**Comment by YFTX2015** [comment]
喔，原来是说给作者听的嘎

**Comment by ZSAIm** [comment]
> 合并问题可以参考这里 [zhangn1985/ykdl#399 (comment)](https://github.com/zhangn1985/ykdl/issues/399#issuecomment-484337220)

OK，下一个版本会使用ffmepg进行所有视频合并操作。
谢谢你的提醒。
