### ISSUE TITLE
爱艺奇一些视频无法下载

### ISSUE THREAD

**Issue by 121786404** [ZSAIm/iqiyi-parser#26]
https://www.iqiyi.com/w_19s7r5kpq1.html
 https://www.iqiyi.com/w_19s865ug09.html
点击下载就卡主了，而且没有error.log

**Comment by ZSAIm** [comment]
第一个链接可能是因为当时改了下载器的多线程字段
第二个是因为文件名存在不合法的字符造成的。

以上两个问题会在下一次更新解决。
