### ISSUE TITLE
清晰度问题

### ISSUE THREAD

**Issue by Tangwenx** [ZSAIm/iqiyi-parser#3]
最高只能支持到720P吗？还有，能不能支持vip视频的下载呢

**Comment by ZSAIm** [comment]
1.这取决于爱奇艺对无需登录用于提供的视频的最高分辨率。
2.目前这程序还不能支持VIP视频，但是如果仅仅是Cookie问题可以使用iqiyi_parse.py里的set_cookie函数。

**Comment by Tangwenx** [comment]
还有一个小问题，最后下载的文件是f4v的，还需要手动ffmpeg封装成mp4，能不能自动下载为mp4呢？

**Comment by ZSAIm** [comment]
应该是不能，因为在分析过程中发现爱奇艺大部分视频只提供了f4v也就是flv的资源。

**Comment by ZSAIm** [comment]
不过你可以在视频合并结尾自行添加视频格式转换工具来实现自动化。

**Comment by Tangwenx** [comment]
好的，感谢
