### ISSUE TITLE
https://v.qq.com还是无法下载

### ISSUE THREAD

**Issue by flfq** [ZSAIm/iqiyi-parser#42]
https://v.qq.com/x/cover/h6sscumuu2bugkg/l00306xchr5.html
提示数据返回为空

**Comment by ZSAIm** [comment]
选择下面的Quanlity，
对于腾讯视频有：

|Quanlity|描述| 
|----|--------|
|1|sd（标清270p）|
|2|sd（标清270p）|
|3|sd（标清270p）|
|4|hd（高清480p）|
|5|shd（超清720p）|
|6|fhd（蓝光1080p）|

是这样一个说明
* 你可以把有无Cookie比作你是否已经登录。
* 然后你从网页段看视频，如果你是已经登录的会员，那么你自然能观看1080p（前提是存在1080p）。反过来看程序，如果同样的，你把会员的Cookie登录导入程序，同样可以解析1080p。
* 但如果你导入的Cookie不是会员，那么你只能选择最高720P，也就Quality<=5，如果你依然选择1080P会提示返回空，是因为你程序收不到被判定为有效的数据，而这主要的原因是因为你导入的不是会员Cookie，所以没有权限观看。这在网页端是显而易见的。
* 没有导入Cookie的不太建议，首先是不能选择720P，重要的是会限速。
* 其实总的来说就是你可以参考网页端的反应来看程序的反应。
