### ISSUE TITLE
腾讯视频 无法下载

### ISSUE THREAD

**Issue by ogli324** [ZSAIm/iqiyi-parser#44]
腾讯视频 添加了VIP cookies 提示请求超时

**Comment by ZSAIm** [comment]
已经更新了腾讯视频的核心了，使用1.6版本以上的程序可以通过菜单Help-Update Cores进行更新核心。

**Comment by ogli324** [comment]
是的 现在可以使用了 非常感谢！

**Comment by cypress-zh** [comment]
大佬，腾讯体育的视频，支持不？
