### ISSUE TITLE
关于爱奇艺下载的相关疑问

### ISSUE THREAD

**Issue by YFTX2015** [ZSAIm/iqiyi-parser#6]
我是爱奇艺 vip，能不能用这个下载1080P视频？还有现在爱奇艺全站视频地址都是以https开头，能够正确解析不？

**Comment by ZSAIm** [comment]
1） 该程序是以游客方式下载视频，不具备下载vip视频。如果你有兴趣可以参考项目目录下的 解析过程.pdf 来分析会员解析方法。
2） 可以解析https，只要是游客能观看的视频都是可以正确解析下载的。
