### ISSUE TITLE
您好，想请问下请求得来的真实ts视频片段地址是如何交由播放器播放的

### ISSUE THREAD

**Issue by JeanLiu820** [ZSAIm/iqiyi-parser#70]

**Comment by ZSAIm** [comment]
我对HLS的加密方式不是很了解，我只能告诉你我知道的和我的猜测，希望能帮到你。

- 腾讯的TS视频应该都是m3u8。抓包不到m3u8文件是因为有时候的m3u8信息是直接放在了proxyhttp的响应里面，并没有单独的请求m3u8文件，所以你会抓不到单独的m3u8文件。这时候直接查看proxyhttp响应应该能找到m3u8的内容。
- SAMPLE-AES加密方式我不了解，但如果SAMPLE-AES加密方式不是一种常见的加密算法的话，那可能是腾讯修改了hls流播放器的的解密方式，从而使得能在h5播放器中实现解密hls流并播放视频。
- 因为现在腾讯视频用的是H5播放器，所以理论上来说播放器的SAMPLE-AES的解密算法都是在前端的，所以是可以通过阅读播放器的代码来了解SAMPLE-AES解密的方式。

**Comment by lcj20180712** [comment]
> 我对HLS的加密方式不是很了解，我只能告诉你我知道的和我的猜测，希望能帮到你。
> 
> * 腾讯的TS视频应该都是m3u8。抓包不到m3u8文件是因为有时候的m3u8信息是直接放在了proxyhttp的响应里面，并没有单独的请求m3u8文件，所以你会抓不到单独的m3u8文件。这时候直接查看proxyhttp响应应该能找到m3u8的内容。
> * SAMPLE-AES加密方式我不了解，但如果SAMPLE-AES加密方式不是一种常见的加密算法的话，那可能是腾讯修改了hls流播放器的的解密方式，从而使得能在h5播放器中实现解密hls流并播放视频。
> * 因为现在腾讯视频用的是H5播放器，所以理论上来说播放器的SAMPLE-AES的解密算法都是在前端的，所以是可以通过阅读播放器的代码来了解SAMPLE-AES解密的方式。

感谢您的回答，事实上我今天上午已经从proxyhttp的json返回中找到所有的m3u8文件标签以及所有的ts流数据并且可以下载到本地进行合成。但我的目的并非单纯的破解vip视频，我的目的是为了给公司项目找到一种合适的DRM加密方案（我是一名JAVA后端工程师，现在在一家小公司担任项目经理）。我的问题有两个，如果您有答案希望您能帮忙解惑（如有明显的漏洞或者错误，请您不要见笑，我目前只是一个普通的开发者，并未像您一样有极高的造诣）：
> *  1 proxyhttp 返回的是json 并非m3u8所代表的hls协议规定的hls文件流，腾讯是如何做到接着json后继续hls协议规定的下一步操作的呢，是否是重写了video播放器的源码，您曾经有看过这里的东西吗。

> *  2 看了您的文章后，我也感兴趣的是腾讯为什么使用如此复杂的混淆规则，如果说是为了加密，可是我从找到proxyhttp以后就已经终结了他的加密。那他是否是为了防止模拟请求吗？可是即使用户知道了所有请求的参数又如何呢，关于用户权限的判断始终是在服务器进行的，如果该用户不是vip，那么他将永远请求不到vip用户能看到的数据。。。如果这也不是，那他的真实目的是为了什么呢？我相信您研究了这么久一定有答案了，可否传授与我呢。。。


最后可以加一下您的联系方式吗，我经常会思考一些很底层的问题，在使用别人造的轮子前我对轮子的实现目的以及关键节点的问题很感兴趣，您的文章都是一些很底层的东西。希望能和您成为朋友有空探讨更多的问题！我的微信是：z827721712 谢谢！
另外关于加密的问题我很苦恼，因为好像连腾讯这样的大公司都没有办法对需要版权保护的视频进行保护，我也尝试过DASH流，可我司用的react-native的框架对于dash流的支持并不是很好，而且在ios上似乎有些问题（我司前端水平有限，无法解决），请问您有研究过Dash流吗？

**Comment by ZSAIm** [comment]
微信就不加了。如果有什么不方便直接说的就是用邮箱吧：zzsaim@163.com

1. hls流的解析最重要的就是协议，也就是m3u8的内容。并且请求m3u8文件就是为了获取其内容。所以这当然是可以实现的，并且必然的，我觉得是说不上是重写，可能只是调用了一些hls流解析的内部接口。而且这一切都是前端的操作，都是可以实现的。我是没有研究过这些播放器，但是道理以我所了解应该还是这个道理。
2. 确实是这样。试想如果你是vip用户，并且你也有想拥有这份资源呢？这是不是有必要加密请求了呢？这样做我觉得是应该理解成是为了避免用户的持有资源，并不是防止用户窃取资源。

以目前我的知识所理解的是任何的版权保护方法都没法彻底的。
任何可以呈现在用户屏幕的视频都已经是视频资源的获取。这也表明了任何的视频的加密都是可以通过逆向来实现解密的。很多时候这只是一个难易的问题而已。加密就是一道门槛，它是无法完全避免资源的泄露的。所以这就需要你自己来权衡视频保护和用户观看体验了。
前面我也说了，对视频流的处理方案我并不是很了解，所以很多时候我只能是以逆向的角度来表达一些我的看法。
