### ISSUE TITLE
API实现

### ISSUE THREAD

**Issue by gaoljhy** [ZSAIm/iqiyi-parser#73]
有考虑过API的实现么？便于二次开发以及调用，调试
可以加个微信么？我很有想法去帮助实现这个

**Comment by ZSAIm** [comment]
有考虑过重构项目，原本是想先重构了nbdler下载模块后再实现，但是最近实习没啥时间呀。

**Comment by ZSAIm** [comment]
有兴趣可以邮箱zzsaim@163.com交流呀

**Comment by gaoljhy** [comment]
哈哈，我也想助力，但是不知道怎么沟通，可以拉群，一起干呀

**Comment by ZSAIm** [comment]
随便创了个Q群，有兴趣的可以加入呀。
# 978635506

还有，，捣乱的别加呀。(╯‵□′)╯︵┻━┻
